### ISSUE TITLE
Building with custom shield

### ISSUE THREAD

**Issue by JostBrand** [lilyinstarlight/zmk-nix#130]
Hi, I want to use the flake similar to the person in the issue #97. I tried to mimic the folder structure but the `nix run .#flash` can not pickup my definition.  In the flake.nix I defined `shield = "plusOne_%PART%"` Is there a special folder structure that I have to respect? PlusOne is just a copy of the cradio definition which I want to use as a baseline for my adjustments later on.

```
.
├── boards
│   └── shields
│       └── plusOne
│           ├── Kconfig.defconfig
│           ├── Kconfig.shield
│           ├── plusOne.conf
│           ├── plusOne.dtsi
│           ├── plusOne.keymap
│           ├── plusOne.zmk.yml
│           ├── plusOne_left.overlay
│           ├── plusOne_right.conf
│           └── plusOne_right.overlay
├── config
│   ├── plusOne.conf
│   ├── plusOne.keymap
│   └── west.yml
├── flake.lock
└── flake.nix
```

Build output:
```

Loading Zephyr default modules (Zephyr base).
-- Application: /build/source/zmk/app
-- CMake version: 3.29.6
-- Found Python3: /nix/store/wfbjq35kxs6x83c3ncpfxdyl5gbhdx4h-python3-3.12.6/bin/python3.12 (found suitable version "3.12.6", mi>
-- Cache files will be written to: /build/source/zephyr/.cache
-- Zephyr version: 3.5.0 (/build/source/zephyr), build: 339570e2393b108bf8f9241018ecaf5615c25469
-- Found west (found suitable version "1.2.0", minimum required is "0.14.0")
-- ZMK Config directory: /build/source/config
-- ZMK Config Kconfig: /build/source/config/plusOne.conf
-- Using keymap file: /build/source/config/plusOne.keymap
-- Board: nice_nano_v2
-- Shield(s): plusOne_left
No shield named 'plusOne_left' found
```

Much appreciated if you could point me into the right direction :yellow_heart:

**Comment by lilyinstarlight** [comment]
Put the `boards` directory into `config/`, this is where ZMK checks for it by default in user config: <https://github.com/zmkfirmware/zmk/blob/7d8dd64cdc2f75f421638c6876de2e9f71e24df2/app/keymap-module/modules/modules.cmake#L51-L54>

Alternatively, you could pass in `-DBOARD_ROOT` to cmake flags, but it would be a bit awkward since it requires an absolute path (i.e. you'd have to get the path from within the builder and append it to `$westBuildFlagsArray`)

**Comment by lilyinstarlight** [comment]
Actually ZMK builds now defaults their template to itself operate as a zephyr module which can do this without awkward flags and with your original directory structure. I'll try to make this work out-of-the-box real quick :)

**Comment by JostBrand** [comment]
Thank you very much for your effort. As you said I can confirm that It works on my end when putting it into config. Maybe worth putting it into the readme for future readers :+1:

**Comment by lilyinstarlight** [comment]
> Maybe worth putting it into the readme for future readers

As mentioned, I'm going to make it work out-of-the-box as the newer unified zmk config repo does, so that will be unnecessary when I finish that today

**Comment by lilyinstarlight** [comment]
Apologies it took a few days, but it's been fixed in the last several commits which I just pushed
